openapi: 3.0.1
info:
  title: Rencana Kinerja User
  description: Data dan Action halaman Perencanaan / Rencana Kinerja Pegawai
  version: 0.0.1
  contact:
    name: Ryan B
    url: "https://github.com/RyanB1303"
    email: ryanb1303@gmail.com
  license:
    name: Apache 2.0
    url: "https://www.apache.org/licenses/LICENSE-2.0"
servers:
  - url: "https://{environment}.kertaskerja.cc/{basePath}"
    description: KertasKerja API Server
    variables:
      environment:
        default: dev
        description: server environment
        enum:
          - dev
          - test
          - prod
      basePath:
        description: path api
        default: api/v1
        enum:
          - api/v1
          - api/v2
paths:
  "/rencana_kinerja/pegawai/{pegawai_id}":
    get:
      summary: list rencana kinerja pegawai
      description: list rencana kinerja pegawai pada tahun terpilih
      parameters:
        - $ref: "#/components/parameters/pegawaiId"
        - $ref: "#/components/parameters/tahun"
      responses:
        "200":
          description: get list rencana kinerja user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RencanaKinerja"
    post:
      summary: simpan rencana kinerja pegawai
      description: simpan rencana kinerja pegawai di form
      parameters:
        - $ref: "#/components/parameters/pegawaiId"
        - $ref: "#/components/parameters/tahun"
      requestBody:
        description: simpan rencana kinerja pegawai
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RencanaKinerja"
components:
  schemas:
    RencanaKinerja:
      type: object
      description: list rencana kinerja user
      properties:
        id:
          type: string
          examples:
            - SAS-PEG-3598
        rencana_kinerja:
          type: string
          examples:
            - Contoh Rencana Kinerja
        tahun:
          type: string
          examples:
            - "2024"
            - 2024_p
        status_rencana_kinerja:
          type: array
          items:
            type: string
          examples:
            - SIAP DITARIK SKP
            - MANRISK SIAP DIVERIFIKASI
        catatan:
          type: string
          examples:
            - "-"
        pegawai_id:
          type: string
          examples:
            - PEG-2021
        indikators:
          type: array
          items:
            $ref: "#/components/schemas/Indikator"
    Indikator:
      type: object
      properties:
        id:
          type: string
          examples:
            - IND-SAS-1234
            - IND-SAS-2222
        sasaran_id:
          type: string
          examples:
            - SAS-PEG-3589
        indikator:
          type: string
          examples:
            - jumlah dokumen perencanaan
            - test a
        target:
          type: integer
          examples:
            - 6
            - 7
        satuan:
          type: string
          examples:
            - dokumen
            - gambar
    Action:
      type: object
      properties:
        name:
          type: string
          examples:
            - InputRincianKak
            - Edit
            - Hapus
        uri:
          type: string
          examples:
            - "/rencana_kinerja/{sasaran_id}/rincian_kak"
            - "/rencana_kinerja/{sasaran_id}/edit"
            - "/rencana_kinerja/{sasaran_id}/hapus"
        method:
          type: string
          examples:
            - GET
            - GET
            - DELETE
  parameters:
    tahun:
      name: tahun
      required: true
      in: query
      description: tahun aktif
      schema:
        type: string
      example: 2024
    pegawaiId:
      name: pegawai_id
      description: id pegawai
      required: true
      in: path
      example: PEG-2021
      schema:
        type: string
